### ISSUE TITLE
setThreadPriority iOS8.0 deprecated

### ISSUE THREAD

**Issue by devcarlos** [vfr/Viewer#1]
I have fixed the setThreadPriority with QualityOfService based on this: http://nshipster.com/nsoperation/

ReaderThumbCache.m
==================

- (id)thumbRequest:(ReaderThumbRequest *)request priority:(BOOL)priority
{
	@synchronized(thumbCache) // Mutex lock
	{
		id object = [thumbCache objectForKey:request.cacheKey];

		if (object == nil) // Thumb object does not yet exist in the cache
		{
			object = [NSNull null]; // Return an NSNull thumb placeholder object

			[thumbCache setObject:object forKey:request.cacheKey cost:2]; // Cache the placeholder object

			ReaderThumbFetch *thumbFetch = [[ReaderThumbFetch alloc] initWithRequest:request]; // Create a thumb fetch operation

			[thumbFetch setQueuePriority:(priority ? NSOperationQueuePriorityNormal : NSOperationQueuePriorityLow)]; // Queue priority

			request.thumbView.operation = thumbFetch;
            
            //iOS7 deprecated
//            [thumbFetch setThreadPriority:(priority ? 0.55 : 0.35)]; // Thread priority
            
            //iOS8 QualityOfService http://nshipster.com/nsoperation/
            //        Quality of Service Constants
            //        Constants indicating the priority with which system resources are given to the operation
            //
            //        Declaration
            //        OBJECTIVE-C
            //#define NSOperationQualityOfService                  NSQualityOfService
            //#define NSOperationQualityOfServiceUserInteractive   NSQualityOfServiceUserInteractive
            //#define NSOperationQualityOfServiceUserInitiated     NSQualityOfServiceUserInitiated
            //#define NSOperationQualityOfServiceUtility           NSQualityOfServiceUtility
            //#define NSOperationQualityOfServiceBackground        NSQualityOfServiceBackground
            
            //        NSOperationQualityOfServiceUserInteractive
            //        The operation corresponds to a graphically interactive task, involving scrolling or animation in some form. Because they are user interactive, operations with this service level are given the highest priority for any needed system resources.
            //
            //            Available in iOS 8.0 and later.
            //
            //        NSOperationQualityOfServiceUserInitiated
            //        The operation corresponds to a task that the user initiated. Tasks with this service level are given a relatively high priority for system resources because they were initiated by the user and therefore correspond to work the user wants done soon.
            //
            //            Available in iOS 8.0 and later.
            //
            //        NSOperationQualityOfServiceUtility
            //        The operation corresponds to tasks initiated by the app but reflecting relatively important work being done on behalf of the user. Tasks with this service level are given a medium priority for system resources.
            //
            //            Available in iOS 8.0 and later.
            //
            //        NSOperationQualityOfServiceBackground
            //        The operation corresponds to tasks that are initiated by the app and represent noncritical tasks. Operations with this priority are given the lowest priority for system resources.
            //            
            //            Available in iOS 8.0 and later.
            
            //set QualityOfService for NSOperationQualityOfServiceUtility
            thumbFetch.qualityOfService = NSQualityOfServiceUtility; // QoS

			[[ReaderThumbQueue sharedInstance] addLoadOperation:thumbFetch]; // Queue the operation
		}

		return object; // NSNull or UIImage
	}
}

NOTE: Same fix on ReaderThumbFetch.m
=================================

- (void)main
{
	CGImageRef imageRef = NULL; NSURL *thumbURL = [self thumbFileURL];

	CGImageSourceRef loadRef = CGImageSourceCreateWithURL((__bridge CFURLRef)thumbURL, NULL);

	if (loadRef != NULL) // Load the existing thumb image
	{
		imageRef = CGImageSourceCreateImageAtIndex(loadRef, 0, NULL); // Load it

		CFRelease(loadRef); // Release CGImageSource reference
	}
	else // Existing thumb image not found - so create and queue up a thumb render operation on the work queue
	{
		ReaderThumbRender *thumbRender = [[ReaderThumbRender alloc] initWithRequest:request]; // Create a thumb render operation

		[thumbRender setQueuePriority:self.queuePriority];
        
        //iOS7 deprecated
//        [thumbRender setThreadPriority:(self.threadPriority - 0.1)]; // Priority
        
        //iOS8 QualityOfService http://nshipster.com/nsoperation/
//        Quality of Service Constants
//        Constants indicating the priority with which system resources are given to the operation
//        
//        Declaration
//        OBJECTIVE-C
//#define NSOperationQualityOfService                  NSQualityOfService
//#define NSOperationQualityOfServiceUserInteractive   NSQualityOfServiceUserInteractive
//#define NSOperationQualityOfServiceUserInitiated     NSQualityOfServiceUserInitiated
//#define NSOperationQualityOfServiceUtility           NSQualityOfServiceUtility
//#define NSOperationQualityOfServiceBackground        NSQualityOfServiceBackground
        
//        NSOperationQualityOfServiceUserInteractive
//        The operation corresponds to a graphically interactive task, involving scrolling or animation in some form. Because they are user interactive, operations with this service level are given the highest priority for any needed system resources.
//            
//            Available in iOS 8.0 and later.
//            
//        NSOperationQualityOfServiceUserInitiated
//        The operation corresponds to a task that the user initiated. Tasks with this service level are given a relatively high priority for system resources because they were initiated by the user and therefore correspond to work the user wants done soon.
//            
//            Available in iOS 8.0 and later.
//                
//        NSOperationQualityOfServiceUtility
//        The operation corresponds to tasks initiated by the app but reflecting relatively important work being done on behalf of the user. Tasks with this service level are given a medium priority for system resources.
//            
//            Available in iOS 8.0 and later.
//            
//        NSOperationQualityOfServiceBackground
//        The operation corresponds to tasks that are initiated by the app and represent noncritical tasks. Operations with this priority are given the lowest priority for system resources.
//            
//            Available in iOS 8.0 and later.
        
        //set QualityOfService for NSQualityOfServiceUserInteractive
        thumbRender.qualityOfService = NSQualityOfServiceUserInteractive; // Priority

		if (self.isCancelled == NO) // We're not cancelled - so update things and add the render operation to the work queue
		{
			request.thumbView.operation = thumbRender; // Update the thumb view operation property to the new operation

			[[ReaderThumbQueue sharedInstance] addWorkOperation:thumbRender]; return; // Queue the operation
		}
	}

	if (imageRef != NULL) // Create a UIImage from a CGImage and show it
	{
		UIImage *image = [UIImage imageWithCGImage:imageRef scale:request.scale orientation:UIImageOrientationUp];

		CGImageRelease(imageRef); // Release the CGImage reference from the above thumb load code

		UIGraphicsBeginImageContextWithOptions(image.size, YES, request.scale); // Graphics context

		[image drawAtPoint:CGPointZero]; // Decode and draw the image on this background thread

		UIImage *decoded = UIGraphicsGetImageFromCurrentImageContext(); // Newly decoded image

		UIGraphicsEndImageContext(); // Cleanup after the bitmap-based graphics drawing context

		[[ReaderThumbCache sharedInstance] setObject:decoded forKey:request.cacheKey]; // Cache it

		if (self.isCancelled == NO) // Show the image in the target thumb view on the main thread
		{
			ReaderThumbView *thumbView = request.thumbView; // Target thumb view for image show

			NSUInteger targetTag = request.targetTag; // Target reference tag for image show

			dispatch_async(dispatch_get_main_queue(), // Queue image show on main thread
			^{
				if (thumbView.targetTag == targetTag) [thumbView showImage:decoded];
			});
		}
	}

	request.thumbView.operation = nil; // Break retain loop
}

**Comment by antypang** [comment]
Thanks ! help me a lot!
