### ISSUE TITLE
Swiping getting stuck

### ISSUE THREAD

**Issue by helmesjo** [vfr/Viewer#2]
If you swipe casually through a pdf (swiping quick seems to be working) it will eventually get stuck, and when you try to swipe the page just flickers but stays at the same page. If you pinch-zoom out and release it will start working again (just to get stuck soon enough).

Currently running on an iPhone 5, iOS 7.1.

This happens in the example.

**Comment by palusik86** [comment]
Same happen to me.

**Comment by helmesjo** [comment]
Probably related to the Reader, see #88 & #89!
