### ISSUE TITLE
Submit to App store?

### ISSUE THREAD

**Issue by thibaultmol** [vfr/Viewer#6]
Hi, I really like using open source and I would love to use this app app on my ipad. Why don't you publish it to the store?

If you don't want to publish it. Maybe it would good to have a section on your website or the readme.md where you list "apps that use the code"

**Comment by vfr** [comment]
This project is now deprecated - it will no longer be maintained. Please see the [UXReader PDF Framework for iOS](https://github.com/vfr/UXReader-iOS) project for its replacement.
